### ISSUE TITLE
GBPUSD

### ISSUE THREAD

**Issue by maxi82** [InduPrakash/yahoofinance#1]
Hello, I am trying to use your integrations for currency conversion and having issue with that. 

I have following configuration but  get no data back. 

Please do let me know if its possible.

  - platform: yahoofinance
    scan_interval:
      hours: 4
    symbols:
      - USDGBP

Kind Regards,

**Comment by InduPrakash** [comment]
Are you looking for USD to GBP conversion rate? Yahoo is not providing any data for USDGBP.

But you can create a sensor like this:
```
- platform: rest
  resource: https://api.exchangeratesapi.io/latest?base=USD&symbols=GBP
  name: usd_gbp
  scan_interval:
    hours: 4
  value_template: '{{ float(value_json.rates.GBP) | round(2) }}'
```
